### ISSUE TITLE
Run a dictionaries for prod and staging

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-subquery#161]
Following https://academy.subquery.network/academy/tutorials_examples/dictionary.html#, it makes sense for us to create a dictionary so that the re-indexing process is going quicker. As we cannot deploy the dictionaries directly on onFinality deployment (see https://t.me/c/1726084536/2 for more), the deployment will have to be performed locally. Therefore, the steps are following:

- [x] Clone https://github.com/bgodlin/sora-subquery-dictionary to `sora-xor` organisation
- [x] Deploy two projects (`prod` and `staging` branches)

**Comment by f33r0** [comment]
subquery.q1.tst.sora2.soramitsu.co.jp - prod node with dict
subquery1.q1.tst.sora2.soramitsu.co.jp - stage node
@bgodlin please check
