### ISSUE TITLE
NPM package `@sora-substrate/type-definitions` depends on lodash but doesn't declare it

### ISSUE THREAD

**Issue by jsdw** [sora-xor/sora-subquery#23]
The package `@sora-substrate/type-definitions` imports lodash in it's `index.{ts|js}` file, but it's not explicitly listed as a dependency in `package.json`. This, I believe, is the cause of an issue that cropped up with a package that depends on it:

https://github.com/PureStake/moonbeam/pull/676

(which led to https://github.com/paritytech/txwrapper-core/issues/130 and then https://github.com/polkadot-js/apps/issues/6107)

Apologies if this is not the right place to post this issue; the `@sora-substrate/type-definitions` has no github link in its package.json and so it's not obvious to me where to report potential issues with it :)

The fix for this I believe is just to add `lodash` to the dependencies in `packags.json` for the `@sora-substrate/type-definitions` package, making the dependency explicit and making sure it's installed as needed downstream.

**Comment by pgolovkin** [comment]
@jsdw Thanks for the feedback! The team will work on it!
@stefashkaa please review and help :-)

**Comment by stefashkaa** [comment]
@jsdw Hello! Thank you for this issue!

`lodash` as a dependency of `@sora-substrate/type-definitions` was a temporary solution which was fixed the issue for `@open-web3/orml-type-definitions` package. I'll check the status of that issue and remove its usage if it was already fixed. If not - I'll add it explicitly to the dependencies of `@sora-substrate/type-definitions`.
