### ISSUE TITLE
ADAR extrinsics support

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-subquery#312]
Problem
Neither incoming transfers nor outgoing transfers caused by ADAR (https://github.com/soramitsu/adar-web) extrinsics (`swapTransfer` and `swapTransferBatch`) are currently being handled by Subquery. As a result, these transfers are not displayed in the transaction history.

Solution
To address this issue, it is necessary to support the aforementioned ADAR extrinsics in Subquery

**Comment by Tieumsan** [comment]
@bgodlin what is the status of this ?

**Comment by bgodlin** [comment]
Completed as part of https://github.com/sora-xor/sora-subquery/commit/0d0e3c1ccacb31c6481d1416b33ac685ad0544bb and https://github.com/sora-xor/sora-subquery/commit/5953e41aded4ccb01e8ccc293b93db1dba40b60a
